package IULIA.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Block = 0;
  public static final int Expression = 1;
  public static final int FunctionCall = 2;
  public static final int FunctionDeclaration = 3;
  public static final int NumberLiteral = 4;
  public static final int Statement = 5;
  public static final int TypeName = 6;
  public static final int Variable = 7;
  public static final int VariableDeclaration = 8;
  public static final int VariableReference = 9;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x9a2567510ab846dfL, 0x90914d2e5bd895b0L);
    builder.put(0x466a47dd28404d01L, Block);
    builder.put(0x466a47dd28405750L, Expression);
    builder.put(0x466a47dd2840580aL, FunctionCall);
    builder.put(0x466a47dd284057b8L, FunctionDeclaration);
    builder.put(0x466a47dd2841596aL, NumberLiteral);
    builder.put(0x466a47dd284057b9L, Statement);
    builder.put(0x466a47dd284057f4L, TypeName);
    builder.put(0x466a47dd284057c1L, Variable);
    builder.put(0x466a47dd28404d02L, VariableDeclaration);
    builder.put(0x466a47dd2841a202L, VariableReference);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
