package IULIA.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt_a0a = ((SAbstractConcept) concept);
    switch (index_xbvbvu_a0a.index(cncpt_a0a)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Block_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new FunctionDeclaration_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new NumberLiteral_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new TypeName_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Variable_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new VariableDeclaration_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new VariableReference_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt_a0d = concept;
    switch (index_xbvbvu_a0d.index(cncpt_a0d)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new FunctionCall_SubstituteMenu());
      case 1:
        return Collections.<SubstituteMenu>singletonList(new VariableReference_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex index_xbvbvu_a0a = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x9a2567510ab846dfL, 0x90914d2e5bd895b0L, 0x466a47dd28404d01L), MetaIdFactory.conceptId(0x9a2567510ab846dfL, 0x90914d2e5bd895b0L, 0x466a47dd284057b8L), MetaIdFactory.conceptId(0x9a2567510ab846dfL, 0x90914d2e5bd895b0L, 0x466a47dd2841596aL), MetaIdFactory.conceptId(0x9a2567510ab846dfL, 0x90914d2e5bd895b0L, 0x466a47dd284057f4L), MetaIdFactory.conceptId(0x9a2567510ab846dfL, 0x90914d2e5bd895b0L, 0x466a47dd284057c1L), MetaIdFactory.conceptId(0x9a2567510ab846dfL, 0x90914d2e5bd895b0L, 0x466a47dd28404d02L), MetaIdFactory.conceptId(0x9a2567510ab846dfL, 0x90914d2e5bd895b0L, 0x466a47dd2841a202L)).seal();
  private static final ConceptSwitchIndex index_xbvbvu_a0d = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x9a2567510ab846dfL, 0x90914d2e5bd895b0L, 0x466a47dd2840580aL), MetaIdFactory.conceptId(0x9a2567510ab846dfL, 0x90914d2e5bd895b0L, 0x466a47dd2841a202L)).seal();
}
